# Generated by Django 5.2 on 2025-04-23 16:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightinstance',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='flightinstance',
            name='base_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=10),
        ),
        migrations.AddField(
            model_name='flightinstance',
            name='business_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('400.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='flightinstance',
            name='business_seats_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flightinstance',
            name='economy_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='flightinstance',
            name='economy_seats_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flightinstance',
            name='first_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('800.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='flightinstance',
            name='first_seats_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='business_seats',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='economy_seats',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='first_seats',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
