# Generated by Django 5.2 on 2025-04-23 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_flightinstance_available_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightschedule',
            name='typical_arrival_time',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
    ]
